name: Sync Leetcode

on:
  workflow_dispatch: # Allows you to run it manually whenever you want
  schedule:
    - cron: '0 0 * * *' # Automatically runs every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Code
        uses: joshcai/leetcode-sync@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.CSRFTOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-solutions
